### ISSUE TITLE
Unable to start tournament

### ISSUE THREAD

**Issue by joscandreu** [radareorg/r2wars#1]
Hello,
When I press start after loading 2 x86 warriors (the ones in the examples)  the web interface does nothing.
I only see this on the console:
```
r2path =  radare2.exe
RES = NOK
```
I am running Ubuntu 18.04. Is there any way to give you more information about this?

**Comment by radare** [comment]
you dont need to copy windows binaries on linux. just run it with mono like this:

mono r2wars.exe examples/

* click load warriors button
* click start buton

**Comment by joscandreu** [comment]
I was not copying any windows binary on linux.
Originally I was running: "./r2wars.exe" with a "warriors" folder at the same location of the bin.
However trying "mono r2wars.exe examples/" continues to leave  me without the execution of the warriors. All that I am able to see is this:
![r2wars](https://user-images.githubusercontent.com/1180443/43852786-740cc906-9b3e-11e8-8caf-62f22f0a774d.png)

Warriors seem to get loaded (even it detects multiple architectures), however when I press start I see nothing. The screen stays the same, just like in the screenshot.

**Comment by jhscheer** [comment]
Hi,
I guess I have the same issue.
I created a `warriors` folder, copied two warriors from `examples` and ran `mono bin/Debug/r2wars.exe`. After clicking `Load Warriors` the warriors are detected but then nothing happens when I click `start`.

**Comment by retauks** [comment]
Hi, sorry ear about this, please can u give me a output of command:
r2 -v
I think the problem is the r2 version used

**Comment by jhscheer** [comment]
`radare2 2.9.0-git 19202 @ linux-x86-64 git.2.8.0-12-gaa0581ab8
commit: aa0581ab818d2ec3f226e0f604d0639c2c5d2ecc build: 2018-08-08__18:26:32`

**Comment by retauks** [comment]
ok,  i think problem is solved at last relese.
https://github.com/radareorg/r2wars/releases/tag/0.2.0
run as usual: mono r2wars.exe

Plz let us know if that solve yours issues.

**Comment by jhscheer** [comment]
No, for me the last release didn't solve it.
Still nothing happens after clicking `start`.

(btw. I had to change `msbuild` back to `xbuild`)

**Comment by radare** [comment]
Why dont you use the zip we distribute in the releases page? You dont have to compile anything.
But if so, msbuild works fine for me. And skuater said that xbuild is deprecated

**Comment by retauks** [comment]
Hi, do you can try it the release zip?

Also ... plz send me more info about OS used, i tested this on Ubuntu 18.04 x64 installing mono as described on mono webpage. And work without problems. 

Another problem will be u have a services listen on websocket port  9966, check for that and if u are compiling the code try changing both ports on program.cs

if u agree, join to #radare on telegram or irc and send me a private message

**Comment by jhscheer** [comment]
My issue is solved, thanks @skuater !
The mono version in my repo was too old and I had to install the latest mono version from the [project site](https://www.mono-project.com/download/stable/).

I also had to use `http://127.0.0.1:9664/` instead of `http://localhost:9664/`

**Comment by retauks** [comment]
Yw, please  @joscandreu confirms if the last release work for you, so we can close the issue. tnx

**Comment by joscandreu** [comment]
I am not going to be able to confirm if it's solved for a few a days as I
won't have access to the machine these days.
Feel free to close the issue, if when I am able to check the issue I see
that it's not resolved I can reopen it (I guess...)

It makes sense it's the mono version. As I installed it from apt repos.
Maybe it is pretty old.

I could also reproduce the issue with Ubuntu 14.04 and mono installed from
apt repos.
